[DEFAULT]
mail.server=smtp.gmail.com
mail.port=587
mail.username=shreygoyal2203
mail.send_from=shreygoyal2203@gmail.com
mail.send_to=shreygoyal2203@gmail.com
mail.subject=Portfolio Performance Report
mail.body=Please find the attached Daily Portfolio Performance Report.
mail.password=rdvs qkyk qsou ewjw
