const applicationConfig = {
    heatmapDropdownOptions: ["BROAD MARKET INDICES", "SECTORAL INDICES", "NIFTY 50","NIFTY NEXT 50","NIFTY 100","NIFTY 200","NIFTY 500","NIFTY MIDCAP 150","NIFTY SMALLCAP 250","NIFTY MICROCAP 250","NIFTY BANK","NIFTY AUTO","NIFTY FINANCIAL SERVICES","NIFTY FMCG","NIFTY IT","NIFTY MEDIA","NIFTY METAL","NIFTY PHARMA","NIFTY PSU BANK","NIFTY PRIVATE BANK","NIFTY REALTY","NIFTY HEALTHCARE INDEX","NIFTY CONSUMER DURABLES","NIFTY OIL & GAS","NIFTY INDIA CONSUMPTION","NIFTY CPSE","NIFTY ENERGY","NIFTY INFRASTRUCTURE", "NIFTY INDIA DEFENCE"]
};

export default applicationConfig;